services:
  - type: web
    name: laravel-image-gallery
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    buildCommand: |
      npm install && npm run build
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
